# Generated by Django 4.2.3 on 2023-07-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
        ('shop', '0003_translations'),
    ]

    operations = [
    ]
